export const STORAGE_KEY = 'probetas-local-db'

export const SECTION_ORDER = [
  'PROBETA',
  'FIBRAS_REFUERZO',
  'PRE-IMPREGNADO',
  'RECETAS',
  'FABRICANTE',
  'PRE-IMPREGNADO_TYPE',
  'RESINA_SYSTEM',
]

export const PROBETA_STEPS = ['Capas', 'Curado', 'Resultados']

export const TABLE_LABELS = {
  PROBETA: 'Probeta',
  ACABADO: 'Acabados',
  DIRECCION_CAPA: 'Direcciones de capa',
  FIBRAS_REFUERZO: 'Fibras de refuerzo',
  'PRE-IMPREGNADO': 'Pre impregnado',
  RECETAS: 'Recetas',
  FABRICANTE: 'Fabricante',
  'PRE-IMPREGNADO_TYPE': 'Tricotado',
  RESINA_SYSTEM: 'Sistema de resina',
}

export const FIELD_LABELS = {
  title: 'Titulo',
  author: 'Autor',
  reviewed: 'Revisado por',
  receta_id: 'Receta',
  referencia: 'Referencia',
  text_id: 'Codigo de ensayo',
  alias: 'Nombre',
  type_id: 'Tricotado',
  fabricante_id: 'Fabricante',
  espesor_curado: 'Espesor curado',
  espesor_sin_curar: 'Espesor sin curar',
  resina_system_id: 'Sistema de resina',
  resina_volume: 'Volumen de resina',
  fibra_refuerzo_id: 'Fibra de refuerzo 1',
  fibra_refuerzo2_id: 'Fibra de refuerzo 2',
  pdf_mds_url: 'PDF MDS',
  pdf_msdt_url: 'PDF MSDT',
  nombre: 'Nombre',
  descripcion: 'Descripcion',
  temperatura_inicial_c: 'Temperatura inicial',
  temperatura_final_c: 'Temperatura final',
  pico_temperatura_c: 'Pico máximo de temperatura',
  temp_tiempo_min: 'Tiempo de temperatura ( min )',
  temp_control_mode: 'Control de temperatura',
  temperatura_c: 'Temperatura actual ( °C )',
  temp_grados_por_min: 'Rampa de temperatura ( °C / min )',
  temp_final_c: 'Temperatura final ( °C )',
  temp_dwell: 'Dwell (Mantenimiento)',
  presion_bar: 'Presion actual ( bar(g) )',
  pres_bar_por_min: 'Rampa de presion ( bar(g) / min )',
  pres_tiempo_min: 'Tiempo de presion ( min )',
  pres_control_mode: 'Control de presion',
  pres_final_bar: 'Presion final ( bar(g) )',
  pres_dwell: 'Dwell (Mantenimiento)',
  vacio_mbar: 'Vacio actual ( bar(g) )',
  vacio_mbar_por_min: 'Rampa de vacio ( bar(g) / min )',
  vacio_tiempo_min: 'Tiempo de vacio ( min )',
  vacio_control_mode: 'Control de vacio',
  vacio_final_mbar: 'Vacio final ( bar(g) )',
  vacio_dwell: 'Dwell (Mantenimiento)',
  largo_mm: 'Largo [mm]',
  ancho_mm: 'Ancho [mm]',
  espesor_mm: 'Espesor [mm]',
  espesor: 'Espesor',
  t1: 'T1',
  t2: 'T2',
  t3: 'T3',
  t4: 'T4',
  t5: 'T5',
  t6: 'T6',
  t7: 'T7',
  t8: 'T8',
  has_uncured_thickness: 'Espesor curado',
  espesor_sin_curado: 'Espesor medio sin curado',
  uncured_t1: 'T1 sin curado',
  uncured_t2: 'T2 sin curado',
  uncured_t3: 'T3 sin curado',
  uncured_t4: 'T4 sin curado',
  uncured_t5: 'T5 sin curado',
  uncured_t6: 'T6 sin curado',
  uncured_t7: 'T7 sin curado',
  uncured_t8: 'T8 sin curado',
  weight_g: 'Peso [g]',
  density: 'Densidad [g/cm3]',
  anotaciones: 'Anotaciones',
  acabado_id: 'Acabado',
  has_acabado_cara_b: 'Acabado cara B',
  acabado_cara_b_id: 'Acabado cara B',
  direccion_id: 'Direccion',
  pre_impregnado_id: 'Material',
}

export const SIMPLE_SECTION_FIELDS = {
  ACABADO: [{ name: 'alias', type: 'text' }],
  FIBRAS_REFUERZO: [
    { name: 'alias', type: 'text' },
    { name: 'pdf_mds_url', type: 'text' },
  ],
  'PRE-IMPREGNADO': [
    { name: 'text_id', type: 'text' },
    { name: 'type_id', type: 'int8', references: 'PRE-IMPREGNADO_TYPE.id' },
    { name: 'fabricante_id', type: 'int8', references: 'FABRICANTE.id' },
    { name: 'espesor_curado', type: 'float8' },
    { name: 'espesor_sin_curar', type: 'float8' },
    { name: 'resina_system_id', type: 'int8', references: 'RESINA_SYSTEM.id' },
    { name: 'resina_volume', type: 'float4' },
    { name: 'fibra_refuerzo_id', type: 'int8', references: 'FIBRAS_REFUERZO.id' },
    { name: 'fibra_refuerzo2_id', type: 'int8', references: 'FIBRAS_REFUERZO.id' },
    { name: 'pdf_mds_url', type: 'text' },
    { name: 'pdf_msdt_url', type: 'text' },
  ],
  RECETAS: [
    { name: 'nombre', type: 'text' },
    { name: 'descripcion', type: 'text' },
    { name: 'temperatura_inicial_c', type: 'float4' },
    { name: 'temperatura_final_c', type: 'float4' },
  ],
  FABRICANTE: [{ name: 'alias', type: 'text' }],
  'PRE-IMPREGNADO_TYPE': [{ name: 'alias', type: 'text' }],
  RESINA_SYSTEM: [
    { name: 'alias', type: 'text' },
    { name: 'pdf_mds_url', type: 'text' },
    { name: 'pdf_msdt_url', type: 'text' },
  ],
}

export const SIMPLE_SECTION_TABLE_FIELDS = {
  'PRE-IMPREGNADO': [
    { name: 'text_id', type: 'text' },
    { name: 'type_id', type: 'int8', references: 'PRE-IMPREGNADO_TYPE.id' },
    { name: 'espesor_curado', type: 'float8' },
    { name: 'espesor_sin_curar', type: 'float8' },
    { name: 'fibra_refuerzo_id', type: 'int8', references: 'FIBRAS_REFUERZO.id' },
    { name: 'fibra_refuerzo2_id', type: 'int8', references: 'FIBRAS_REFUERZO.id' },
    { name: 'pdf_mds_url', type: 'text' },
    { name: 'pdf_msdt_url', type: 'text' },
  ],
}

export const RECETA_STEP_FIELDS = [
  { name: 'temperatura_c', type: 'float4' },
  { name: 'temp_grados_por_min', type: 'float4' },
  { name: 'temp_tiempo_min', type: 'float4' },
  { name: 'temp_control_mode', type: 'text' },
  { name: 'temp_final_c', type: 'float4' },
  { name: 'temp_dwell', type: 'bool' },
  { name: 'presion_bar', type: 'float4' },
  { name: 'pres_bar_por_min', type: 'float4' },
  { name: 'pres_tiempo_min', type: 'float4' },
  { name: 'pres_control_mode', type: 'text' },
  { name: 'pres_final_bar', type: 'float4' },
  { name: 'pres_dwell', type: 'bool' },
  { name: 'vacio_mbar', type: 'float4' },
  { name: 'vacio_mbar_por_min', type: 'float4' },
  { name: 'vacio_tiempo_min', type: 'float4' },
  { name: 'vacio_control_mode', type: 'text' },
  { name: 'vacio_final_mbar', type: 'float4' },
  { name: 'vacio_dwell', type: 'bool' },
]
